name:                db-lesson
version:             0.1.0.0
github:              "pennychase/db-lesson"
license:             BSD3
author:              "Penny Chase"
maintainer:          "mpchase136@gmail.com"
copyright:           "2021 Penny Chase"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pennychase/db-lesson#readme>

dependencies:
- base >= 4.7 && < 5
- time
- sqlite-simple

default-extensions:
- OverloadedStrings

library:
  source-dirs: src
  exposed-modules:
  - SchemaTypes
  - DatabaseCommands

executables:
  db-lesson-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - db-lesson

tests:
  db-lesson-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - db-lesson
